from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('myview', views.myview, name='myview'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('create', views.create, name='create'),
    path('list', views.lista, name='list'),
    path('fileupload', views.fileupload, name='fileupload'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('edit/update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('ajax/', views.ajax, name='ajax'),
    path('ajax/ajax', views.ajax, name='ajaxpost'),
    path('ajax/delete', views.ajax_delete, name='ajax_delete'),
    path('ajax/getajax', views.getajax, name='getajax'),
    path('register', views.register, name='register'),
    path('register/success/', views.register_success, name='register_success'),
    path('users/', views.users, name='users'),
    path('jsonresponse/ausers', views.ausers, name='ausers'),
    path('users/delete/<int:id>', views.user_delete, name='user_delete'),
    path('upload/csv/', views.upload_csv, name='upload_csv'),
    path('change_password', views.changePassword, name='changePassword'),
    path('file/delete', views.changePassword, name='changePassword'),
    path('file/delete/<int:id>', views.deleteFiles, name='deleteFiles'),
    path('storeuser', views.storeuser, name='storeuser'),
    path('edituser/<int:id>', views.edituser, name='edituser'),
    path('deleteuser/<int:id>', views.deleteuser, name='deleteuser'),
    path('profile/', views.profile, name='profile'),
    path('saveprofile/<int:id>', views.saveprofile, name='saveprofile'),
]
